version: '2'
services:
  homepage:
    image: daocloud.io/hithinksoft/homepage
    restart: always
    ports:
      - 808:8080
    links:
      - db

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123789456
      - MYSQL_DATABASE=homepage
      - MYSQL_USER=homepage_manager
      - MYSQL_PASSWORD=homepage_manager123789456
    ports:
      - 3306:3306
    volumes:
      - homepage:/var/lib/mysql

volumes:
  homepage:
    driver: local
